[[plugins]]
repo = 'lervag/vimtex'
on_ft = 'tex'
hook_source='''
    let g:vimtex_compiler_latexmk = {
        \ 'background' : 0,
        \ 'build_dir' : '',
        \ 'continuous' : 1,
        \ 'options' : [,
        \ '-pdfdvi',
        \ '-verbose',
        \ '-file-line-error',
        \ '-syntax=1',
        \ '-interaction=nonstopmode',
        \],
        \}
'''


[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_event = 'InsertEnter'
hook_source = '''
    let g:deoplete#enable_at_startup = 1
    let g:deoplete#auto_complete_delay = 0
    let g:deoplete#auto_complete_start_length = 1
    set completeopt-=preview
'''

[[plugins]]
repo = 'zchee/deoplete-clang'
on_ft = ['c','cpp']
depends = 'deoplete.nvim'
hook_add = '''
    let g:deoplete#sources#clang#libclang_path = '/usr/lib64/libclang.so'
    let g:deoplete#sources#clang#clang_header = '/usr/lib64/clang/3.8.0/include/'
'''


[[plugins]]
repo = 'Shougo/neosnippet.vim'
dpends = 'deoplete.nvim'
